name: build-image

on:
  push:
    branches:
      - "release-2.0"
    tags:
      - "v*"
    paths:
      - "**.go"

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Tag
        id: extract_tag
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin registry.cn-shanghai.aliyuncs.com

      - name: Run buildx
        run: |
          tag="${{ steps.extract_branch.outputs.branch }}"

          echo extract_tag   ${{ steps.extract_tag.outputs.version }}
          echo extract_branch  ${{ steps.extract_branch.outputs.branch }}
          echo current tag is ${tag}

          docker buildx build --platform linux/amd64,linux/arm64 --push -t registry.cn-shanghai.aliyuncs.com/openhydra/core-api-server:${tag} .
